/* Generated by re2c 0.13.5 on Fri Mar 14 14:27:10 2014 */
#line 1 "libgringo/src/input/nongroundlexer.xh"
// {{{ GPL License 

// This file is part of gringo - a grounder for logic programs.
// Copyright (C) 2013  Roland Kaminski

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// }}}

// TODO: think about making location tracking easier
//       and allow for using newlines in SHOWSIG and PYTHON again

#define YYCTYPE     char
#define YYCURSOR    cursor()
#define YYLIMIT     limit()
#define YYMARKER    marker()
#define YYCTXMARKER ctxmarker()
#define YYFILL(n)   {fill(n);}

#line 44 "libgringo/src/input/nongroundlexer.xh"


int Gringo::Input::NonGroundParser::lex_impl(void *pValue, Location &loc) {
start:
    int bc = 0;
    start();
    loc.beginFilename = filename();
    loc.beginLine     = line();
    loc.beginColumn   = column();
    auto &value = *static_cast<Gringo::Input::NonGroundGrammar::parser::semantic_type*>(pValue);
    
#line 46 "build/release/libgringo/src/input/nongroundlexer.hh"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy3;
	case '\n':	goto yy4;
	case '!':	goto yy55;
	case '"':	goto yy18;
	case '#':	goto yy6;
	case '$':	goto yy68;
	case '%':	goto yy70;
	case '&':	goto yy60;
	case '(':	goto yy33;
	case ')':	goto yy35;
	case '*':	goto yy45;
	case '+':	goto yy41;
	case ',':	goto yy25;
	case '-':	goto yy43;
	case '.':	goto yy21;
	case '/':	goto yy56;
	case '0':	goto yy13;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy15;
	case ':':	goto yy23;
	case ';':	goto yy19;
	case '<':	goto yy51;
	case '=':	goto yy53;
	case '>':	goto yy49;
	case '?':	goto yy66;
	case '@':	goto yy58;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy16;
	case '[':	goto yy29;
	case '\\':	goto yy47;
	case ']':	goto yy31;
	case '^':	goto yy62;
	case '_':	goto yy10;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy12;
	case 'n':	goto yy8;
	case '{':	goto yy37;
	case '|':	goto yy27;
	case '}':	goto yy39;
	case '~':	goto yy64;
	default:	goto yy72;
	}
yy2:
#line 55 "libgringo/src/input/nongroundlexer.xh"
	{ goto start; }
#line 155 "build/release/libgringo/src/input/nongroundlexer.hh"
yy3:
	yych = *++YYCURSOR;
	goto yy274;
yy4:
	++YYCURSOR;
#line 56 "libgringo/src/input/nongroundlexer.xh"
	{ if(eof()) return 0; step(); goto start; }
#line 163 "build/release/libgringo/src/input/nongroundlexer.hh"
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '!':	goto yy133;
	case 'c':	goto yy137;
	case 'd':	goto yy135;
	case 'e':	goto yy142;
	case 'f':	goto yy139;
	case 'i':	goto yy141;
	case 'm':	goto yy136;
	case 'p':	goto yy143;
	case 's':	goto yy138;
	case 't':	goto yy140;
	default:	goto yy7;
	}
yy7:
#line 133 "libgringo/src/input/nongroundlexer.xh"
	{ lexerError(string()); goto start; }
#line 183 "build/release/libgringo/src/input/nongroundlexer.hh"
yy8:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'o':	goto yy130;
	default:	goto yy127;
	}
yy9:
#line 71 "libgringo/src/input/nongroundlexer.xh"
	{ value.uid = FWString::uid(string()); return NonGroundGrammar::parser::token::IDENTIFIER; }
#line 193 "build/release/libgringo/src/input/nongroundlexer.hh"
yy10:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy122;
	case '_':	goto yy128;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy126;
	default:	goto yy11;
	}
yy11:
#line 74 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::ANONYMOUS; }
#line 256 "build/release/libgringo/src/input/nongroundlexer.hh"
yy12:
	yych = *++YYCURSOR;
	goto yy127;
yy13:
	++YYCURSOR;
yy14:
#line 72 "libgringo/src/input/nongroundlexer.xh"
	{ value.num = integer(); return NonGroundGrammar::parser::token::NUMBER; }
#line 265 "build/release/libgringo/src/input/nongroundlexer.hh"
yy15:
	yych = *++YYCURSOR;
	goto yy125;
yy16:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy123;
yy17:
#line 73 "libgringo/src/input/nongroundlexer.xh"
	{ value.uid = FWString::uid(string()); return NonGroundGrammar::parser::token::VARIABLE; }
#line 276 "build/release/libgringo/src/input/nongroundlexer.hh"
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy7;
	default:	goto yy118;
	}
yy19:
	++YYCURSOR;
#line 85 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::SEM; }
#line 288 "build/release/libgringo/src/input/nongroundlexer.hh"
yy21:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '.':	goto yy115;
	default:	goto yy22;
	}
yy22:
#line 87 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::DOT; }
#line 298 "build/release/libgringo/src/input/nongroundlexer.hh"
yy23:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy113;
	case '~':	goto yy111;
	default:	goto yy24;
	}
yy24:
#line 88 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::COLON; }
#line 309 "build/release/libgringo/src/input/nongroundlexer.hh"
yy25:
	++YYCURSOR;
#line 91 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::COMMA; }
#line 314 "build/release/libgringo/src/input/nongroundlexer.hh"
yy27:
	++YYCURSOR;
#line 92 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::VBAR; }
#line 319 "build/release/libgringo/src/input/nongroundlexer.hh"
yy29:
	++YYCURSOR;
#line 93 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::LBRACK; }
#line 324 "build/release/libgringo/src/input/nongroundlexer.hh"
yy31:
	++YYCURSOR;
#line 94 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::RBRACK; }
#line 329 "build/release/libgringo/src/input/nongroundlexer.hh"
yy33:
	++YYCURSOR;
#line 95 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::LPAREN; }
#line 334 "build/release/libgringo/src/input/nongroundlexer.hh"
yy35:
	++YYCURSOR;
#line 96 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::RPAREN; }
#line 339 "build/release/libgringo/src/input/nongroundlexer.hh"
yy37:
	++YYCURSOR;
#line 97 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::LBRACE; }
#line 344 "build/release/libgringo/src/input/nongroundlexer.hh"
yy39:
	++YYCURSOR;
#line 98 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::RBRACE; }
#line 349 "build/release/libgringo/src/input/nongroundlexer.hh"
yy41:
	++YYCURSOR;
#line 99 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::ADD; }
#line 354 "build/release/libgringo/src/input/nongroundlexer.hh"
yy43:
	++YYCURSOR;
#line 100 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::SUB; }
#line 359 "build/release/libgringo/src/input/nongroundlexer.hh"
yy45:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy109;
	default:	goto yy46;
	}
yy46:
#line 103 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::MUL; }
#line 369 "build/release/libgringo/src/input/nongroundlexer.hh"
yy47:
	++YYCURSOR;
#line 102 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::MOD; }
#line 374 "build/release/libgringo/src/input/nongroundlexer.hh"
yy49:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy107;
	default:	goto yy50;
	}
yy50:
#line 104 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::GT; }
#line 384 "build/release/libgringo/src/input/nongroundlexer.hh"
yy51:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy105;
	case '>':	goto yy103;
	default:	goto yy52;
	}
yy52:
#line 105 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::LT; }
#line 395 "build/release/libgringo/src/input/nongroundlexer.hh"
yy53:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy101;
	default:	goto yy54;
	}
yy54:
#line 111 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::ASSIGN; }
#line 405 "build/release/libgringo/src/input/nongroundlexer.hh"
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy99;
	default:	goto yy7;
	}
yy56:
	++YYCURSOR;
#line 112 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::SLASH; }
#line 416 "build/release/libgringo/src/input/nongroundlexer.hh"
yy58:
	++YYCURSOR;
#line 113 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::AT; }
#line 421 "build/release/libgringo/src/input/nongroundlexer.hh"
yy60:
	++YYCURSOR;
#line 114 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::AND; }
#line 426 "build/release/libgringo/src/input/nongroundlexer.hh"
yy62:
	++YYCURSOR;
#line 115 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::XOR; }
#line 431 "build/release/libgringo/src/input/nongroundlexer.hh"
yy64:
	++YYCURSOR;
#line 116 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::BNOT; }
#line 436 "build/release/libgringo/src/input/nongroundlexer.hh"
yy66:
	++YYCURSOR;
#line 117 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::QUESTION; }
#line 441 "build/release/libgringo/src/input/nongroundlexer.hh"
yy68:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '!':	goto yy77;
	case '*':	goto yy83;
	case '+':	goto yy87;
	case '-':	goto yy85;
	case '<':	goto yy75;
	case '=':	goto yy79;
	case '>':	goto yy81;
	default:	goto yy69;
	}
yy69:
#line 118 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP; }
#line 458 "build/release/libgringo/src/input/nongroundlexer.hh"
yy70:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy73;
	default:	goto yy71;
	}
yy71:
#line 131 "libgringo/src/input/nongroundlexer.xh"
	{ goto comment; }
#line 468 "build/release/libgringo/src/input/nongroundlexer.hh"
yy72:
	yych = *++YYCURSOR;
	goto yy7;
yy73:
	++YYCURSOR;
#line 130 "libgringo/src/input/nongroundlexer.xh"
	{ bc++; goto blockcomment; }
#line 476 "build/release/libgringo/src/input/nongroundlexer.hh"
yy75:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy95;
	case '>':	goto yy97;
	default:	goto yy76;
	}
yy76:
#line 123 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_LT; }
#line 487 "build/release/libgringo/src/input/nongroundlexer.hh"
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy93;
	default:	goto yy78;
	}
yy78:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy7;
	case 1: 	goto yy11;
	case 2: 	goto yy69;
	case 3: 	goto yy161;
	case 4: 	goto yy187;
	case 5: 	goto yy197;
	case 6: 	goto yy250;
	case 7: 	goto yy258;
	}
yy79:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy91;
	default:	goto yy80;
	}
yy80:
#line 127 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_EQ; }
#line 515 "build/release/libgringo/src/input/nongroundlexer.hh"
yy81:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy89;
	default:	goto yy82;
	}
yy82:
#line 125 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_GT; }
#line 525 "build/release/libgringo/src/input/nongroundlexer.hh"
yy83:
	++YYCURSOR;
#line 121 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_MUL; }
#line 530 "build/release/libgringo/src/input/nongroundlexer.hh"
yy85:
	++YYCURSOR;
#line 120 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_SUB; }
#line 535 "build/release/libgringo/src/input/nongroundlexer.hh"
yy87:
	++YYCURSOR;
#line 119 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_ADD; }
#line 540 "build/release/libgringo/src/input/nongroundlexer.hh"
yy89:
	++YYCURSOR;
#line 124 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_GEQ; }
#line 545 "build/release/libgringo/src/input/nongroundlexer.hh"
yy91:
	++YYCURSOR;
#line 126 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_EQ; }
#line 550 "build/release/libgringo/src/input/nongroundlexer.hh"
yy93:
	++YYCURSOR;
#line 128 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_NEQ; }
#line 555 "build/release/libgringo/src/input/nongroundlexer.hh"
yy95:
	++YYCURSOR;
#line 122 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_LEQ; }
#line 560 "build/release/libgringo/src/input/nongroundlexer.hh"
yy97:
	++YYCURSOR;
#line 129 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CSP_NEQ; }
#line 565 "build/release/libgringo/src/input/nongroundlexer.hh"
yy99:
	++YYCURSOR;
#line 109 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::NEQ; }
#line 570 "build/release/libgringo/src/input/nongroundlexer.hh"
yy101:
	++YYCURSOR;
#line 108 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::EQ; }
#line 575 "build/release/libgringo/src/input/nongroundlexer.hh"
yy103:
	++YYCURSOR;
#line 110 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::NEQ; }
#line 580 "build/release/libgringo/src/input/nongroundlexer.hh"
yy105:
	++YYCURSOR;
#line 107 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::LEQ; }
#line 585 "build/release/libgringo/src/input/nongroundlexer.hh"
yy107:
	++YYCURSOR;
#line 106 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::GEQ; }
#line 590 "build/release/libgringo/src/input/nongroundlexer.hh"
yy109:
	++YYCURSOR;
#line 101 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::POW; }
#line 595 "build/release/libgringo/src/input/nongroundlexer.hh"
yy111:
	++YYCURSOR;
#line 90 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::WIF; }
#line 600 "build/release/libgringo/src/input/nongroundlexer.hh"
yy113:
	++YYCURSOR;
#line 89 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::IF; }
#line 605 "build/release/libgringo/src/input/nongroundlexer.hh"
yy115:
	++YYCURSOR;
#line 86 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::DOTS; }
#line 610 "build/release/libgringo/src/input/nongroundlexer.hh"
yy117:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy118:
	switch (yych) {
	case '\n':	goto yy78;
	case '"':	goto yy120;
	case '\\':	goto yy119;
	default:	goto yy117;
	}
yy119:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\\':
	case 'n':	goto yy117;
	default:	goto yy78;
	}
yy120:
	++YYCURSOR;
#line 75 "libgringo/src/input/nongroundlexer.xh"
	{ value.uid = FWString::uid(unquote(string(1, 1))); return NonGroundGrammar::parser::token::STRING; }
#line 636 "build/release/libgringo/src/input/nongroundlexer.hh"
yy122:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy123:
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy122;
	default:	goto yy17;
	}
yy124:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy125:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	default:	goto yy14;
	}
yy126:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy127:
	switch (yych) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy126;
	default:	goto yy9;
	}
yy128:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy122;
	case '_':	goto yy128;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy126;
	default:	goto yy78;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy131;
	default:	goto yy127;
	}
yy131:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy126;
	default:	goto yy132;
	}
yy132:
#line 70 "libgringo/src/input/nongroundlexer.xh"
	{ value.uid = not_; return NonGroundGrammar::parser::token::NOT; }
#line 937 "build/release/libgringo/src/input/nongroundlexer.hh"
yy133:
	++YYCURSOR;
#line 132 "libgringo/src/input/nongroundlexer.xh"
	{ goto comment; }
#line 942 "build/release/libgringo/src/input/nongroundlexer.hh"
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy265;
	default:	goto yy78;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy248;
	case 'i':	goto yy247;
	default:	goto yy78;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy238;
	default:	goto yy78;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy181;
	case 'h':	goto yy182;
	case 'u':	goto yy183;
	default:	goto yy78;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy176;
	default:	goto yy78;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy172;
	default:	goto yy78;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy159;
	default:	goto yy78;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy151;
	default:	goto yy78;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy144;
	default:	goto yy78;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy145;
	default:	goto yy78;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy146;
	default:	goto yy78;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy147;
	default:	goto yy78;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy148;
	default:	goto yy78;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy149;
	default:	goto yy78;
	}
yy149:
	++YYCURSOR;
#line 65 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::BLOCK; }
#line 1034 "build/release/libgringo/src/input/nongroundlexer.hh"
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy152;
	default:	goto yy78;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy153;
	default:	goto yy78;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy154;
	default:	goto yy78;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy155;
	default:	goto yy78;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy156;
	default:	goto yy78;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy157;
	default:	goto yy78;
	}
yy157:
	++YYCURSOR;
#line 66 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::EXTERNAL; }
#line 1075 "build/release/libgringo/src/input/nongroundlexer.hh"
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy162;
	case 'f':	goto yy160;
	default:	goto yy78;
	}
yy160:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy168;
	default:	goto yy161;
	}
yy161:
#line 67 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::INFIMUM; }
#line 1093 "build/release/libgringo/src/input/nongroundlexer.hh"
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy163;
	default:	goto yy78;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy164;
	default:	goto yy78;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy165;
	default:	goto yy78;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy166;
	default:	goto yy78;
	}
yy166:
	++YYCURSOR;
#line 59 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::INCLUDE; }
#line 1122 "build/release/libgringo/src/input/nongroundlexer.hh"
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy169;
	default:	goto yy78;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy170;
	default:	goto yy78;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy171;
	default:	goto yy78;
	}
yy171:
	yych = *++YYCURSOR;
	goto yy161;
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy173;
	default:	goto yy78;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy174;
	default:	goto yy78;
	}
yy174:
	++YYCURSOR;
#line 77 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::TRUE; }
#line 1160 "build/release/libgringo/src/input/nongroundlexer.hh"
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy177;
	default:	goto yy78;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy178;
	default:	goto yy78;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy179;
	default:	goto yy78;
	}
yy179:
	++YYCURSOR;
#line 78 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::FALSE; }
#line 1183 "build/release/libgringo/src/input/nongroundlexer.hh"
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy216;
	default:	goto yy78;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy195;
	default:	goto yy78;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy184;
	case 'p':	goto yy186;
	default:	goto yy78;
	}
yy184:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '+':	goto yy193;
	default:	goto yy185;
	}
yy185:
#line 79 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::SUM; }
#line 1212 "build/release/libgringo/src/input/nongroundlexer.hh"
yy186:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'r':	goto yy188;
	default:	goto yy187;
	}
yy187:
#line 68 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::SUPREMUM; }
#line 1223 "build/release/libgringo/src/input/nongroundlexer.hh"
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy189;
	default:	goto yy78;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy190;
	default:	goto yy78;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy191;
	default:	goto yy78;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy192;
	default:	goto yy78;
	}
yy192:
	yych = *++YYCURSOR;
	goto yy187;
yy193:
	++YYCURSOR;
#line 80 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::SUMP; }
#line 1255 "build/release/libgringo/src/input/nongroundlexer.hh"
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy196;
	default:	goto yy78;
	}
yy196:
	YYCTXMARKER = YYCURSOR + 1;
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy198;
	case '$':
	case '-':	goto yy200;
	case '_':	goto yy202;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy204;
	default:	goto yy197;
	}
yy197:
#line 60 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::SHOW; }
#line 1305 "build/release/libgringo/src/input/nongroundlexer.hh"
yy198:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy198;
	case '$':
	case '-':	goto yy200;
	case '_':	goto yy202;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy204;
	default:	goto yy78;
	}
yy200:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy200;
	case '_':	goto yy202;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy204;
	default:	goto yy78;
	}
yy202:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '_':	goto yy202;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy204;
	default:	goto yy78;
	}
yy204:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy206;
	case '\'':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy204;
	case '/':	goto yy208;
	default:	goto yy78;
	}
yy206:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy206;
	case '/':	goto yy208;
	default:	goto yy78;
	}
yy208:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy208;
	case '0':	goto yy210;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy212;
	default:	goto yy78;
	}
yy210:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy210;
	case '.':	goto yy214;
	default:	goto yy78;
	}
yy212:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy210;
	case '.':	goto yy214;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy212;
	default:	goto yy78;
	}
yy214:
	++YYCURSOR;
	YYCURSOR = YYCTXMARKER;
#line 61 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::SHOWSIG; }
#line 1566 "build/release/libgringo/src/input/nongroundlexer.hh"
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy217;
	default:	goto yy78;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy218;
	default:	goto yy78;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy219;
	default:	goto yy78;
	}
yy219:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy219;
	case '(':	goto yy221;
	default:	goto yy78;
	}
yy221:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 6) YYFILL(6);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy221;
	case 'l':	goto yy224;
	case 'p':	goto yy223;
	default:	goto yy78;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy230;
	default:	goto yy78;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy225;
	default:	goto yy78;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy226;
	default:	goto yy78;
	}
yy226:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy226;
	case ')':	goto yy228;
	default:	goto yy78;
	}
yy228:
	++YYCURSOR;
#line 58 "libgringo/src/input/nongroundlexer.xh"
	{ goto lua; }
#line 1641 "build/release/libgringo/src/input/nongroundlexer.hh"
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy231;
	default:	goto yy78;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy232;
	default:	goto yy78;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy233;
	default:	goto yy78;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy234;
	default:	goto yy78;
	}
yy234:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy234;
	case ')':	goto yy236;
	default:	goto yy78;
	}
yy236:
	++YYCURSOR;
#line 57 "libgringo/src/input/nongroundlexer.xh"
	{ goto python; }
#line 1681 "build/release/libgringo/src/input/nongroundlexer.hh"
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy240;
	case 'u':	goto yy239;
	default:	goto yy78;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy244;
	default:	goto yy78;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy241;
	default:	goto yy78;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy242;
	default:	goto yy78;
	}
yy242:
	++YYCURSOR;
#line 62 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::CONST; }
#line 1711 "build/release/libgringo/src/input/nongroundlexer.hh"
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy245;
	default:	goto yy78;
	}
yy245:
	++YYCURSOR;
#line 81 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::COUNT; }
#line 1722 "build/release/libgringo/src/input/nongroundlexer.hh"
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy257;
	default:	goto yy78;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy249;
	default:	goto yy78;
	}
yy249:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy251;
	default:	goto yy250;
	}
yy250:
#line 83 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::MAX; }
#line 1745 "build/release/libgringo/src/input/nongroundlexer.hh"
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy252;
	default:	goto yy78;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy253;
	default:	goto yy78;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':
	case 'z':	goto yy254;
	default:	goto yy78;
	}
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy255;
	default:	goto yy78;
	}
yy255:
	++YYCURSOR;
#line 64 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::MAXIMIZE; }
#line 1775 "build/release/libgringo/src/input/nongroundlexer.hh"
yy257:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'i':	goto yy259;
	default:	goto yy258;
	}
yy258:
#line 82 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::MIN; }
#line 1786 "build/release/libgringo/src/input/nongroundlexer.hh"
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy260;
	default:	goto yy78;
	}
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy261;
	default:	goto yy78;
	}
yy261:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':
	case 'z':	goto yy262;
	default:	goto yy78;
	}
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy263;
	default:	goto yy78;
	}
yy263:
	++YYCURSOR;
#line 63 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::MINIMIZE; }
#line 1816 "build/release/libgringo/src/input/nongroundlexer.hh"
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy266;
	default:	goto yy78;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'j':	goto yy267;
	default:	goto yy78;
	}
yy267:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy268;
	default:	goto yy78;
	}
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy269;
	default:	goto yy78;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy270;
	default:	goto yy78;
	}
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy271;
	default:	goto yy78;
	}
yy271:
	++YYCURSOR;
#line 84 "libgringo/src/input/nongroundlexer.xh"
	{ return NonGroundGrammar::parser::token::DISJOINT; }
#line 1857 "build/release/libgringo/src/input/nongroundlexer.hh"
yy273:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy274:
	switch (yych) {
	case '\t':
	case '\r':
	case ' ':	goto yy273;
	default:	goto yy2;
	}
}
#line 134 "libgringo/src/input/nongroundlexer.xh"

python:
    
#line 1874 "build/release/libgringo/src/input/nongroundlexer.hh"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy279;
	case '#':	goto yy277;
	default:	goto yy281;
	}
yy277:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy282;
	default:	goto yy278;
	}
yy278:
#line 142 "libgringo/src/input/nongroundlexer.xh"
	{ goto python; }
#line 1893 "build/release/libgringo/src/input/nongroundlexer.hh"
yy279:
	++YYCURSOR;
#line 141 "libgringo/src/input/nongroundlexer.xh"
	{ if(eof()) { lexerError("<EOF>"); return 0; } step(); goto python; }
#line 1898 "build/release/libgringo/src/input/nongroundlexer.hh"
yy281:
	yych = *++YYCURSOR;
	goto yy278;
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy284;
	default:	goto yy283;
	}
yy283:
	YYCURSOR = YYMARKER;
	goto yy278;
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy285;
	default:	goto yy283;
	}
yy285:
	++YYCURSOR;
#line 137 "libgringo/src/input/nongroundlexer.xh"
	{
            value.uid = FWString::uid(string()+"\n"); 
            return NonGroundGrammar::parser::token::PYTHON; 
        }
#line 1924 "build/release/libgringo/src/input/nongroundlexer.hh"
}
#line 143 "libgringo/src/input/nongroundlexer.xh"

lua:
    
#line 1930 "build/release/libgringo/src/input/nongroundlexer.hh"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy291;
	case '#':	goto yy289;
	default:	goto yy293;
	}
yy289:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy294;
	default:	goto yy290;
	}
yy290:
#line 153 "libgringo/src/input/nongroundlexer.xh"
	{ goto lua; }
#line 1949 "build/release/libgringo/src/input/nongroundlexer.hh"
yy291:
	++YYCURSOR;
#line 152 "libgringo/src/input/nongroundlexer.xh"
	{ if(eof()) { lexerError("<EOF>"); return 0; } step(); goto lua; }
#line 1954 "build/release/libgringo/src/input/nongroundlexer.hh"
yy293:
	yych = *++YYCURSOR;
	goto yy290;
yy294:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy296;
	default:	goto yy295;
	}
yy295:
	YYCURSOR = YYMARKER;
	goto yy290;
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy297;
	default:	goto yy295;
	}
yy297:
	++YYCURSOR;
#line 146 "libgringo/src/input/nongroundlexer.xh"
	{
            std::string s(string(0,4));
            s.erase(0, s.find(')') + 1);
            value.uid = FWString::uid(std::move(s)); 
            return NonGroundGrammar::parser::token::LUA; 
        }
#line 1982 "build/release/libgringo/src/input/nongroundlexer.hh"
}
#line 154 "libgringo/src/input/nongroundlexer.xh"

blockcomment:
    
#line 1988 "build/release/libgringo/src/input/nongroundlexer.hh"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy305;
	case '%':	goto yy303;
	case '*':	goto yy301;
	default:	goto yy307;
	}
yy301:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '%':	goto yy310;
	default:	goto yy302;
	}
yy302:
#line 161 "libgringo/src/input/nongroundlexer.xh"
	{ goto blockcomment; }
#line 2008 "build/release/libgringo/src/input/nongroundlexer.hh"
yy303:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy308;
	default:	goto yy304;
	}
yy304:
#line 159 "libgringo/src/input/nongroundlexer.xh"
	{ goto comment; }
#line 2018 "build/release/libgringo/src/input/nongroundlexer.hh"
yy305:
	++YYCURSOR;
#line 160 "libgringo/src/input/nongroundlexer.xh"
	{ if(eof()) { lexerError("<EOF>"); return 0; } step(); goto blockcomment; }
#line 2023 "build/release/libgringo/src/input/nongroundlexer.hh"
yy307:
	yych = *++YYCURSOR;
	goto yy302;
yy308:
	++YYCURSOR;
#line 158 "libgringo/src/input/nongroundlexer.xh"
	{ bc++; goto blockcomment; }
#line 2031 "build/release/libgringo/src/input/nongroundlexer.hh"
yy310:
	++YYCURSOR;
#line 157 "libgringo/src/input/nongroundlexer.xh"
	{ if(--bc == 0) goto start; goto blockcomment; }
#line 2036 "build/release/libgringo/src/input/nongroundlexer.hh"
}
#line 162 "libgringo/src/input/nongroundlexer.xh"

comment:
    
#line 2042 "build/release/libgringo/src/input/nongroundlexer.hh"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy314;
	default:	goto yy316;
	}
yy314:
	++YYCURSOR;
#line 165 "libgringo/src/input/nongroundlexer.xh"
	{ if(eof()) { if(bc > 0) lexerError("<EOF>"); return 0; } step(); if(bc > 0) goto blockcomment; goto start; }
#line 2055 "build/release/libgringo/src/input/nongroundlexer.hh"
yy316:
	++YYCURSOR;
#line 166 "libgringo/src/input/nongroundlexer.xh"
	{ goto comment; }
#line 2060 "build/release/libgringo/src/input/nongroundlexer.hh"
}
#line 167 "libgringo/src/input/nongroundlexer.xh"

    assert(false);
    return 0;
}

#undef YYCTYPE
#undef YYCURSOR
#undef YYLIMIT
#undef YYMARKER
#undef YYFILL
